name: Lint and test

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        nodejs: [16, 18]

    steps:
      - uses: actions/checkout@v2

      # https://github.com/actions/setup-node
      - uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.nodejs }}

      - run: yarn install
      - run: yarn test
      - run: yarn lint
      - run: yarn build-all
      - run: |
          if [[ $(git status --porcelain) ]]; then
            echo "Encountered uncommitted files:"
            git status --porcelain
            echo ""
            echo "You may need to run `yarn build-all`, commit any changes, and push again."
            exit 1
          fi
